#!/bin/bash

#$ -cwd
#$ -o output.dat
#$ -e error.dat

for i in `seq 0 99`
do 
  cat ../data/exported-tasks-ksakaguchi-2015-05-20.csv |python infer_TS.py ../result/fr-en$i -n 2 -d 0 -s 2 -p 0.5
done

